#! /bin/tcsh -f

# This script will install koala executables at
# $KOALABIN, and creat soft links at $BINPATH
# which point to the executables at $KOALABIN.
# 
# Please make sure $BINPATH is in your $PATH.
#
# Author: Changning Niu (cniu@ncsu.edu)
# Updated at 03-29-2013.


# Where koala executables are stored:
set KOALABIN = $HOME/Apps/koala/bin

# Your default bin path:
set BINPATH = $HOME/bin

# C compiler:
set CC = c++

# Don't change the following.
# Unless you know what you are doing.
if ( `echo $PATH | grep "$BINPATH" | wc -l` == 0 ) then
    echo "Warning: BINPATH ($BINPATH) is not in your PATH!"
    echo "Add $BINPATH to your PATH after installation."
endif
mkdir -p $KOALABIN
mkdir -p $BINPATH
$CC src/koala.cpp -o $KOALABIN/koala
$CC src/koala_dire2cart.cpp -o $KOALABIN/koala_dire2cart
$CC src/koala_elec_entro.cpp -o $KOALABIN/koala_elec_entro
cp src/koala_emto_mur.tcsh $KOALABIN/koala_emto_mur
cp src/koala_espr_mur.tcsh $KOALABIN/koala_espr_mur
cp src/koala_kill.tcsh $KOALABIN/koala_kill
cp src/koala_monitor.tcsh $KOALABIN/koala_monitor
cp src/koala_plot_dos.tcsh $KOALABIN/koala_plot_dos
cp src/koala_plot_mag.tcsh $KOALABIN/koala_plot_mag
cp src/koala_vasp_mur.tcsh $KOALABIN/koala_vasp_mur

cd $KOALABIN
foreach i ( * )
    ln -sf $KOALABIN/$i $BINPATH/$i
end 
